export const FETCH_GAME_DATA_ERROR = 'FETCH_GAME_DATA_ERROR';
export const FETCH_GAME_DATA_SUCCESS = 'FETCH_GAME_DATA_SUCCESS';
export const FETCH_POKEMON_GAMES_ERROR = 'FETCH_POKEMON_GAMES_ERROR';
export const FETCH_POKEMON_GAMES_SUCCESS = 'FETCH_POKEMON_GAMES_SUCCESS';
export const NO_GAME_SELECTED = 'NO_GAME_SELECTED';
export const SELECT_GAME_GENERATION = 'SELECT_GAME_GENERATION';
export const SET_FILTERED_POKEMONS = 'SET_FILTERED_POKEMONS';
